package edu.upenn.cis555.command;

public enum CommandType {
	NODE_UP, 
	CRAWL_INDEX_START, 
	CRAWL_INDEX_END,
	LOCAL_NUM_DOCS_CRAWLED, 
	GLOBAL_NUM_DOCS_CRAWLED, 
	GLOBAL_INDEX_START, 
	GLOBAL_INDEX_COMPLETE,
	DOCUMENT_WEIGHT_CALC_START,
	DOCUMENT_WEIGHT_CALC_COMPLETE,
	DISTRIBUTED_PAGE_RANK_START,
	DISTRIBUTED_PAGE_RANK_COMPLETE,
	OPEN_REST_SERVER,
	CLOSE_REST_SERVER
}
